# Generated by Django 3.2.10 on 2022-01-01 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sku_modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('dali_ref', models.CharField(max_length=100)),
                ('sku_id', models.CharField(max_length=100)),
                ('sku_url', models.CharField(max_length=100)),
                ('catalog', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
                ('min_price', models.CharField(max_length=100)),
                ('max_price', models.CharField(max_length=100)),
                ('unit_cost', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='sku_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.CharField(max_length=20)),
                ('uae_box', models.CharField(max_length=100)),
                ('uae_box_price', models.CharField(max_length=100)),
                ('ksa_box', models.CharField(max_length=100)),
                ('ksa_box_price', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
