# Generated by Django 3.2.10 on 2022-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_modal',
            name='catalog',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sku_modal',
            name='sku_url',
            field=models.CharField(max_length=255),
        ),
    ]
